### ISSUE TITLE
关于自定义三个页面

### ISSUE THREAD

**Issue by JiangShuLiang** [hss01248/PageStateManager#2]
作者你好，我想问一下如果我要自定义三个状态页面，各个页面里的各个view的监听事件怎么实现？

比如现在想自定义一个errorStatePage，里面有个button的监听事件要怎么去实现？

**Comment by hss01248** [comment]
这个button的事件时点击重试?现在点击事件我是加在整个errorStatePage上面,你实现runnable就好了.你一个errorStatePage页面,除了点击重试,没有其他动作了吧?
