### ISSUE TITLE
自定义了三个状态页，报空指针异常。

### ISSUE THREAD

**Issue by JiangShuLiang** [hss01248/PageStateManager#3]
具体错误日志：
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.srwl.www/com.srwl.www.activity.TicketInfoActivity}: java.lang.NullPointerException

Caused by: java.lang.NullPointerException

caused by指向的代码是这句：pageStateManager = PageManager.init(this, "找不到相关航班信息，请返回重新查询", true, new Runnable() {....

我是直接把你的三个状态页的xml文件拿来修改的，里面并没有增加控件，只是改了文字内容和图片内容而已。然后在application中初始化： PageManager.initInApp(getApplicationContext(), R.layout.page_empty,R.layout.pager_loading,R.layout.pager_error);

这样子做应该没错把？

**Comment by hss01248** [comment]
用法没有问题,我试了你的操作,没有空指针啊,你自己debug一下,找到谁为null,然后就好解决了.

**Comment by JiangShuLiang** [comment]
好的！我再多调试看看！感谢！

**Comment by hss01248** [comment]
@JiangShuLiang 
原先代码有逻辑错误,现已修复
