### ISSUE TITLE
有一处错误，看是不是我误会了。

### ISSUE THREAD

**Issue by leguang** [hss01248/PageStateManager#5]
在PageManager类中
`    private void setupRetryLayout(PageListener listener, PageLayout loadingAndRetryLayout) {
        if (listener.isSetRetryLayout()) {
            int layoutId = listener.generateRetryLayoutId();
            if (layoutId != NO_LAYOUT_ID) {
                loadingAndRetryLayout.setLoadingView(layoutId);
            } else {
                loadingAndRetryLayout.setLoadingView(listener.generateRetryLayout());
            }
        } else {
            if (BASE_RETRY_LAYOUT_ID != NO_LAYOUT_ID)
                loadingAndRetryLayout.setRetryView(BASE_RETRY_LAYOUT_ID);
        }
    }`

在setupRetryLayout中是不是应该是setRetryView，你现在全部用的是setLoadingView，请问是不是错位了。

**Comment by hss01248** [comment]
已修复
